theme = "catppuccin_mocha"

[editor]
line-number = "relative"
color-modes = true
bufferline = "always"
popup-border = "all"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.soft-wrap]
enable = true

[keys.normal.space.t]
s = ":toggle soft-wrap.enable"

[editor.file-picker]
hidden = false

[editor.whitespace]
render = "all"

[editor.indent-guides]
render = true

[editor.inline-diagnostics]
cursor-line = "warning"

[keys.insert]
j = { k = "normal_mode" }
